# Generated by Django 3.2.13 on 2022-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0002_alter_question_quest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quest_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
