# Generated by Django 3.2.13 on 2022-05-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='corp_id',
            field=models.ForeignKey(db_column='corp_id', on_delete=django.db.models.deletion.CASCADE, related_name='corp', to='homeapp.corporation', to_field='name'),
        ),
    ]
