# Generated by Django 3.2.13 on 2022-05-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20220509_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='corp_id',
            new_name='corp_name',
        ),
    ]
